gui:
  language: 'en'
  branchColors:
    "feature": "#11aaff"
git:
  diffRenderers:
    - colorArg: always
      command: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  editPreset: "nvim"
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  openCommand: "nvim {{filename}}"
